### ISSUE TITLE
Property icons overlap in Bonofix theme & Dev theme

### ISSUE THREAD

**Issue by Gitbreast** [yoyurec/logseq-awesome-ui#45]
**Info:**
- OS: Newest MacOS
- Logseq ver: 0.8.17
- Plugin ver: 1.6.13
- Theme name: Bonofix theme v3.8.3, Dev theme v1.26.15

- [ ] ⚠ Do i have issue with DISABLED my `custom.css`?

**Description:**
1. "/ea08" property icons overlaps other icons always(in Bonofix).
2. "/ea24" property icons overlaps other icons sometimes(in Bonofix). (Pic2, property "date-saved" has 3 different icons.)
3. A transparent rectangle overlaps every single property icon always(in Bonofix & Dev).
4. Property area shows up with a grey border(in Bonofix & Dev).
(_Property_ means page and block properties.)
(Just tested Bonofix and Dev, haven't test other themes yet.)

**To Reproduce:**
Type the properties in different themes.

**Expected behavior:**
Works like default theme.

**Screenshots**
Default theme:
<img width="572" alt="image" src="https://user-images.githubusercontent.com/96460796/218246263-0d9004f9-adf6-4d89-98b0-a701a7e24e6e.png">
Bonofix theme:
<img width="564" alt="image" src="https://user-images.githubusercontent.com/96460796/218246592-b27cee04-48e7-4e1d-abd7-70262cd76702.png">
Dev theme:
<img width="529" alt="image" src="https://user-images.githubusercontent.com/96460796/218246677-b1aca5e8-8254-4cf9-a7bc-35734f479ab5.png">

**Attach files**
Add (via drag-n-drop) .zip with `.md` files (if it needs) to help with bugfixind

**Comment by yoyurec** [comment]
"Dev theme" gray bg - it is its own issue. author not using reassigning Logseq variables (((

![image](https://user-images.githubusercontent.com/137919/218247939-f02c14e1-70fc-45d7-855c-6b3545c46dad.png)

it should be colored like:
```css
.white-theme, .light-theme, html[data-theme=light], html[data-theme=white] {
    ...
    --ls-page-properties-background-color: var(--ls-secondary-background-color);
    ....
}
.page-properties, .block-properties {
    margin: 0 0 0.5em;
    font-size: 0.8em;
    /* background: var(--ls-secondary-background-color);*/
    width: fit-content;
    padding-right: 2rem;
    max-width: var(--ct-block-max-width);
}
```
